# Open each contrast csv file generated by peak calling
# Take columns and arrange into bed file format

import os
import pandas as pd

dir = 'path-to-dir/Contrasts'
os.mkdir(dir+'/bed_files')

os.chdir(dir)

def cToB(contrast):
    df = pd.read_csv(contrast)
    bed = df[['seqnames', 'start', 'end', 'p.value']].copy()
    bed['name'] = range(len(bed))
    bed = bed.loc[:, ['seqnames', 'start', 'end', 'name','p.value']]
    bed.to_csv(dir+'/bed_files/'+contrast+'.bed.peak.txt', sep='\t', header = True, index=False)

files = [x for x in os.listdir(dir) if '.csv' in x]

for file in files:
    cToB(file)
